server:
  port: 8081

spring:
  application:
    name: geass_media

  datasource:
    url: ${GEASS_DB_URL}
    username: ${GEASS_DB_USERNAME}
    password: ${GEASS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy/MM/dd
    time-zone: Asia/Tokyo

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.geass.media.model
  configuration:
    map-underscore-to-camel-case: true
