# ---------- 构建阶段 ----------
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . ./
ENV NEXT_SKIP_ESLINT=1
RUN npm run build


# ---------- 运行阶段 ----------
FROM node:20-alpine AS runner
WORKDIR /app

# 只复制 standalone 构建产物（不带 dev 依赖）
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

CMD ["node", "server.js"]
